apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-maida-based
spec:

  workspaces:
  - name: main-workspace
  - name: maven-settings
  - name: maven-local-repo
  - name: gitops-workspace

  params:
    - name: APP_SOURCE_GIT
      description: The application git repository
      default: 'http://gitea-oqss-cicd.apps.middleware.rhbr-lab.com/gitea-admin/tekton-pipeline-demo-app'
    - name: APP_SOURCE_BRANCH
      type: string
      default: 'develop'

    - name: APP_MANIFESTS_GIT
      type: string
      default: 'http://gitea-oqss-cicd.apps.middleware.rhbr-lab.com/gitea-admin/oqss-cnp-gitops'

    - name: APP_CONTEXT_DIR
      default: './app-source-code/helloworld'
  tasks:
    - name: source-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: "$(params.APP_SOURCE_BRANCH)"
        - name: depth
          value: '0'
        - name: deleteExisting
          value: 'true'
        - name: sslVerify
          value: 'false'
        - name: subdirectory
          value: 'app-source-code'
      workspaces:
        - name: output
          workspace: main-workspace

    - name: get-commit-info
      taskRef:
        kind: Task
        name: get-git-commit-info
      params:
        - name: BRANCH
          value: $(params.APP_SOURCE_BRANCH)
      workspaces:
        - name: output
          workspace: main-workspace
      runAfter:
        - source-clone

    - name: unit-test
      taskRef:
        kind: Task
        name: maven
      params:    
        - name: GOALS
          value:
            - '--batch-mode'
            - test
            - '-DskipTests=true'
            - '-Denforcer.skip=true'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: $(params.APP_CONTEXT_DIR)
      workspaces:
        - name: source
          workspace: main-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
      runAfter:
        - get-commit-info

    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-Dsonar.host.url=http://sonarqube-sonarqube:9000'  
            - '-Dsonar.userHome=/tmp/sonar'
            - '-DskipTests=true'
            - '-Denforcer.skip=true'
        - name: CONTEXT_DIR
          value: $(params.APP_CONTEXT_DIR)
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: main-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
      runAfter:
        - unit-test

    - name: build-app
      params:
        - name: GOALS
          value:
            - clean
            - package
            - '-DskipTests=true'
            - '-Denforcer.skip=true'
        - name: CONTEXT_DIR
          value: $(params.APP_CONTEXT_DIR)
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: main-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
      runAfter:
        - code-analysis

    - name: archive-app
      params:
        - name: GOALS
          value:
            - deploy
            - '-DskipTests=true'
            - '-Denforcer.skip=true'
        - name: CONTEXT_DIR
          value: $(params.APP_CONTEXT_DIR)
      runAfter:
        - build-app
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: main-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo

    - name: build-image
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: >-
            quay.io/dferreira/helloworld:$(tasks.get-commit-info.results.commit_hash)
        - name: CONTEXT
          value: './app-source-code/helloworld'
      runAfter:
        - archive-app
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: main-workspace

    - name: update-deployment
      params:               
        - name: GIT_REPOSITORY
          value: $(params.APP_MANIFESTS_GIT)
        - name: COMMIT_HASH
          value: $(tasks.get-commit-info.results.commit_hash)
        - name: BRANCH_NAMESPACE
          value: $(tasks.get-commit-info.results.branch_namespace)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: source
          workspace: gitops-workspace