apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-maida-based
spec:

  workspaces:
  - name: main-workspace
  - name: maven-settings
  - name: maven-local-repo
  - name: gitops-workspace

  params:
    - name: APP_SOURCE_GIT
      description: The application git repository
      default: 'http://gitea-david-tekton-pipeline.apps.middleware.rhbr-lab.com/gitea-admin/tekton-pipeline-demo-app'
    - name: APP_SOURCE_BRANCH
      type: string
      default: 'develop'

    - name: APP_MANIFESTS_GIT
      type: string
      default: 'http://gitea-david-tekton-pipeline.apps.middleware.rhbr-lab.com/gitea-admin/tekton-demo-app-manifests'

    - name: APP_CONTEXT_DIR
      default: './app-source-code/helloworld'
  tasks:
    - name: source-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: "$(params.APP_SOURCE_BRANCH)"
        - name: depth
          value: '0'
        - name: deleteExisting
          value: 'true'
        - name: sslVerify
          value: 'false'
        - name: subdirectory
          value: 'app-source-code'
      workspaces:
        - name: output
          workspace: main-workspace

    - name: get-commit-info
      taskRef:
        kind: Task
        name: get-git-commit-info
      workspaces:
        - name: output
          workspace: main-workspace
      runAfter:
        - source-clone

    - name: update-deployment
      params:               
        - name: GIT_REPOSITORY
          value: $(params.APP_MANIFESTS_GIT)  
        - name: HASH_COMMIT
          value: $(tasks.get-commit-info.results.commit_hash)
      runAfter:
        - get-commit-info
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: gitops-workspace