apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-maida-based
spec:

  workspaces:
  - name: main-workspace
  - name: maven-settings
  - name: maven-local-repo

  params:
    - name: APP_SOURCE_GIT
      description: The application git repository
      default: 'https://github.com/redhat-oraex/tekton-pipeline-demo-app'
    - name: APP_SOURCE_BRANCH
      type: string
      default: ''
    - name: APP_CONTEXT_DIR
      default: './app-source-code/helloworld'

  tasks:
    - name: source-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: "$(params.APP_SOURCE_BRANCH)"
        - name: depth
          value: '0'
        - name: deleteExisting
          value: 'true'
        - name: sslVerify
          value: 'false'
        - name: subdirectory
          value: 'app-source-code'
      workspaces:
        - name: output
          workspace: main-workspace

    - name: unit-test
      taskRef:
        kind: Task
        name: maven
      params:    
        - name: GOALS
          value:
            - '--batch-mode'
            - test
            - '-DskipTests=true'
            - '-Denforcer.skip=true'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: $(params.APP_CONTEXT_DIR)
      workspaces:
        - name: source
          workspace: main-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
      runAfter:
        - source-clone

    - name: code-analysis
      params:
        - name: GOALS
          value:
            - install
            - 'sonar:sonar'
            - '-Dsonar.host.url=http://sonarqube-sonarqube:9000'  
            - '-Dsonar.userHome=/tmp/sonar'
            - '-DskipTests=true'
            - '-Denforcer.skip=true'
        - name: CONTEXT_DIR
          value: $(params.APP_CONTEXT_DIR)
      runAfter:
        - unit-test
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: main-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo

    - name: sleep-cinco-mil
      taskRef:
        name: sleep-cinco-mil
        kind: Task
      workspaces:
      - name: main-workspace
        workspace: main-workspace
      runAfter:
      - code-analysis